image: 'maven:latest'
maven-build:
  script: 'mvn install -DskipTests'
  stage: build
maven-test:
  script: 'mvn test'
  stage: test
services:
  - 'mysql:5.7.29'
variables:
  MYSQL_DATABASE: userdb
  MYSQL_HOST: localhost
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: root
  MYSQL_PASSWORD: root123

stages:
  - test
  - build
